server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://PLAYVOICE-USER-SERVICE
          predicates:
            - Path=/api/v1/user-service/**
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /${segment}

        - id: user-service-uploads
          uri: lb://PLAYVOICE-USER-SERVICE
          predicates:
            - Path=/uploads/**

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/v1/post-service/**
          filters:
            - RewritePath=/api/v1/post-service/(?<segment>.*), /${segment}

        - id: comment-service
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comment-service/**
          filters:
            - RewritePath=/api/v1/comment-service/(?<segment>.*), /${segment}

        - id: consulting-service
          uri: lb://CONSULTING-SERVICE
          predicates:
            - Path=/api/v1/consulting-service/**
          filters:
            - RewritePath=/api/v1/consulting-service/(?<segment>.*), /$\{segment}

springdoc:
  swagger-ui:
    urls-primary-name: user-service
    urls:
      - name: user-service
        url: /api/v1/user-service/v3/api-docs
      - name: post-service
        url: /api/v1/post-service/v3/api-docs
      - name: comment-service
        url: /api/v1/comment-service/v3/api-docs
      - name: consulting-service
        url: /api/v1/consulting-service/v3/api-docs